### PR TITLE
Added /CP option

### PR DESCRIPTION
**Pull request by joedf**
See: https://autohotkey.com/boards/viewtopic.php?t=10169

### CODE REVIEW

**Comment by fincs** [comment]
For consistency with AutoHotkey, the default codepage should not be UTF-8. Other than that, it is fine.

**Comment by joedf** [comment]
@fincs Ok, the changes have been made. However, I'm not sure if it is correct since [Compiler.ahk#L57-L58](https://github.com/fincs/Ahk2Exe/blob/50946cf75e1e0f98aa49be96d76bb090ab82df5c/Compiler.ahk#L57-L58) uses `"UTF-8"` verbatim.

**Comment by fincs** [comment]
AutoHotkeySC.bin does need an UTF-8 encoded script embedded as a resource. The code simply converts the script source code into UTF-8 through that StrPut call.

**Comment by joedf** [comment]
Ok, just making sure. :+1:

**Comment by JnLlnd** [comment]
Hi again. If one of you has a moment to take a look at this on the forum. Thanks.
[Issue with latest Ahk2Exe Edge with latest AHK binary file](https://autohotkey.com/boards/viewtopic.php?f=5&t=13155)

**Comment by joedf** [comment]
I've compiled it. I tried a test "hello world" script. Seems to work.
[Ahk2Exe-edge_v1.1.23.00.zip](https://github.com/fincs/Ahk2Exe/files/96064/Ahk2Exe-edge_v1.1.23.00.zip)

**Pull request merged**
